const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pant1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pant',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pant2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pant',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pant3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pant',
    },
    {
      name: 'Nike Air Force',
      slug: 'classic-shoes',
      category: 'Shoes',
      image: '/images/shoe1.jpg',
      price: 100,
      brand: 'Nike',
      rating: 3.4,
      numReviews: 18,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Nike Pro 365',
      slug: 'fit-shoes',
      category: 'Shoes',
      image: '/images/shoe2.jpg',
      price: 120,
      brand: 'Nike',
      rating: 3.1,
      numReviews: 11,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Nike Flex Essential',
      slug: 'sports-shoes',
      category: 'Shoes',
      image: '/images/shoe3.jpg',
      price: 150,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 15,
      countInStock: 20,
      description: 'A popular Shoe',
    },
  ],
};

export default data;
