const data = {
  products: [
    {
      name: 'Iphone X',
      slug: 'iphone-x',
      category: 'Phones',
      image: '/images/phone1.jpg',
      price: 800,
      brand: 'Apple',
      rating: '4.5',
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Phone',
    },
    {
      name: 'Iphone 11',
      slug: 'iphone-xi',
      category: 'Phones',
      image: '/images/phone2.jpg',
      price: 900,
      brand: 'Apple',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Phone',
    },
    {
      name: 'Iphone 12',
      slug: 'iphone-xii',
      category: 'Phones',
      image: '/images/phone3.jpg',
      price: 1000,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular Phone',
    },
    {
      name: 'Xiaomi MI Pad 3',
      slug: 'tab-1',
      category: 'Tabs',
      image: '/images/tab3.jpg',
      price: 400,
      brand: 'Xiaomi',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'A popular tab',
    },
    {
      name: 'Xiaomi MI Pad 5',
      slug: 'tab-2',
      category: 'Tabs',
      image: '/images/tab2.jpg',
      price: 450,
      brand: 'Xiaomi',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular tab',
    },
    {
      name: 'Xiaomi MI Pad 4',
      slug: 'tab-3',
      category: 'Tabs',
      image: '/images/tab1.jpg',
      price: 300,
      brand: 'Xiaomi',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular tab',
    },
    {
      name: 'Xiaomi Earpad 1',
      slug: 'ear-1',
      category: 'Earpads',
      image: '/images/ear1.jpg',
      price: 75,
      brand: 'Xiaomi',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular Earpad',
    },
    {
      name: 'Xiaomi Earpad 2',
      slug: 'ear-2',
      category: 'Earpads',
      image: '/images/ear2.jpg',
      price: 75,
      brand: 'Xiaomi',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular Earpad',
    },
    {
      name: 'Xiaomi Earpad 3',
      slug: 'ear-3',
      category: 'Earpads',
      image: '/images/ear3.jpg',
      price: 75,
      brand: 'Xiaomi',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular Earpad',
    },
    {
      name: 'Nike Air Force',
      slug: 'classic-shoes',
      category: 'Shoes',
      image: '/images/shoe1.jpg',
      price: 100,
      brand: 'Nike',
      rating: 3.4,
      numReviews: 18,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Nike Pro 365',
      slug: 'fit-shoes',
      category: 'Shoes',
      image: '/images/shoe2.jpg',
      price: 120,
      brand: 'Nike',
      rating: 3.1,
      numReviews: 11,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Nike Flex Essential',
      slug: 'sports-shoes',
      category: 'Shoes',
      image: '/images/shoe3.jpg',
      price: 150,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 15,
      countInStock: 20,
      description: 'A popular Shoe',
    },
  ],
};

export default data;
